monitor:
  directory: "./watched"
  interval: 10  # seconds
  alert_email: true

email:
  from: "your_email@example.com"
  to: "admin@example.com"
  smtp_server: "smtp.example.com"
  smtp_port: 465
  username: "your_email@example.com"
  password: "your_email_password"
